version: "3.8"

services:
  backend-service:
    container_name: strapi-cms
    image: giovannilamarmora/strapi-cms:latest
    hostname: app.strapi.cms
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "1337:1337"
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: strapiDB
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SSL: ${DATABASE_SSL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      TRANSFER_TOKEN_SALT: ${TRANSFER_TOKEN_SALT}
    volumes:
      #- ./config:/opt/app/config
      #- ./src:/opt/app/src
      #- ./yarn.lock:/opt/yarn.lock
      #- ./.env:/opt/app/.env
      #- ./public/uploads:/opt/app/public/uploads
      - strapi:/usr/src/api/strapi-app
      - strapi:/srv/app
    networks:
      docker-network:
        aliases:
          - app.strapi.cms
networks:
  docker-network:
    external: true
volumes:
  strapi:
    external: true
    name: app.strapi.cms
